services:
  rust--crash-course:
    container_name: rust-crash-course
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME:-hello}
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - PROJECT_NAME=${PROJECT_NAME:-hello}
    stdin_open: true
    tty: true
    restart: no
